### ISSUE TITLE
Not support with PHP 7.2

### ISSUE THREAD

**Issue by bkmaheta** [deltaaskii/lara-pdf-merger#25]
Replace below lines in tcpdf/tcpdi.php
Line no: 487

`while (list($k, $v) = each($value[1])) {
       $this->_straightOut($k . ' ');
       $this->pdf_write_value($v);
}`

Replace with below
`
foreach ($value[1] as $k => $v) {
       $this->_straightOut($k . ' ');
       $this->pdf_write_value($v);
}
`

**Comment by Ribster** [comment]
Fixes the problem! Thanks!

**Comment by gerbesf** [comment]
Up
