### ISSUE TITLE
PHP 7.3 support?

### ISSUE THREAD

**Issue by oriceon** [deltaaskii/lara-pdf-merger#29]
Hello. Can you please replace continue with break on TCPDF class?

**Comment by RamonSmit** [comment]
How did you get it working on 7.3 anyways? 

I'm getting the following error:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'TCPDI' not found in /application/vendor/lynx39/lara-pdf-merger/src/LynX39/LaraPdfMerger/PdfManage.php:53
```

**Comment by oriceon** [comment]
I replaced continue with break on tcpdf class
