### ISSUE TITLE
Issue on line 487 in file  tctpdi.php when lara-pdf-merger is  installed  via composer update

### ISSUE THREAD

**Issue by SampathKumar27896** [deltaaskii/lara-pdf-merger#30]
An issue on line 487 in file  tctpdi.php when lara-pdf-merger is installed via composer update.
The deprecated 'each' function is left unchanged on the above-mentioned line. But its changed on the latest commit.

**Comment by StefanNeuser** [comment]
use in your composer.json:

`"lynx39/lara-pdf-merger": "dev-master#04e4b38df0a9564f3ad0b21c0bc05d4a3510ef43"`

and than `composer update`

**Comment by SampathKumar27896** [comment]
Thankyou so much. The problem was fixed.
