### ISSUE TITLE
Class 'App\Http\Controllers\LynX39\LaraPdfMerger\PdfManage' not found

### ISSUE THREAD

**Issue by shihjay2** [deltaaskii/lara-pdf-merger#5]
It looks like it was a closed issue (#1) but the issue has resurfaced.  Noted that a May commit had reinserted class PDFManage instead of class PdfManage

**Comment by mndeto** [comment]
Change  

> $pdf = new LynX39\LaraPdfMerger\PdfManage;

 to 

> $pdf = new \LynX39\LaraPdfMerger\PdfManage;
