### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by RamonSmit** [deltaaskii/lara-pdf-merger#6]
Hello Dev,

Thanks for making this epic package! I really appreciate this work.
It's easy and simple to use! 1000 times thanks! 

I have a small question, would you mind to set a tag for version management? 
So we don't have to worry about breaking changes on the composer dev-master branche.

Thanks in advance,
Ramon

**Comment by LynX39** [comment]
Hi @RamonSmit,
we provide to update a tag version in v1.0.*.
Thanks for your support.
Michael
